Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNetCore.Data;
using AspNetCore.Models;
using Microsoft.AspNetCore.Http;
using System.Text;
using LINQtoCSV;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.AspNetCore.SignalR;
using CsvHelper.Configuration;
using CsvHelper;

namespace AspNetCore.Controllers
{
    public class MembersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IHubContext<NotificationHub> _hubContext;

        public MembersController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor, IHubContext<NotificationHub> hubcontext)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            _hubContext = hubcontext;
        }

        // GET: Members
        public async Task<IActionResult> Index(string? currentFilter, string? sortOrder, int? pageNumber, int page = 1, int pageSize = 9, int pageLimit = 5)
        {
            ViewBag.DateSortParam = sortOrder == "date" ? "date_desc" : "date";
            ViewBag.NameSortParam = sortOrder == "name" ? "name_desc" : "name";
            ViewBag.AgeSortParam = sortOrder == "age" ? "age_desc" : "age";
            ViewBag.GenderSortParam = sortOrder == "gender" ? "gender_desc" : "gender";

            ViewBag.CurrentPage = pageNumber;
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentFilter = currentFilter;

            var members = from s in _context.Member
                          select s;

            if (!String.IsNullOrEmpty(currentFilter))
            {
                foreach (string part in currentFilter.Split(' '))
                {
                    if (!string.IsNullOrEmpty(part))
                    {
                        if (!part.Contains(" "))
                        {
                            members = members.Where(s => s.confirmation_date.ToString().Contains(part)
                                                        || s.municipality_code.Contains(part)
                                                        || s.municipality_name.Contains(part)
                                                        || s.age_bracket.Contains(part)
                                                        || s.gender.Contains(part));
                        }
                    }
                }
            }

            switch (sortOrder)
            {
                case "date":
                    members = members.OrderBy(s => s.confirmation_date);
                    break;
                case "date_desc":
                    members = members.OrderByDescending(s => s.confirmation_date);
                    break;
                case "name":
                    members = members.OrderBy(s => s.municipality_name);
                    break;
                case "name_desc":
                    members = members.OrderByDescending(s => s.municipality_name);
                    break;
                case "age":
                    members = members.OrderBy(s => s.age_bracket);
                    break;
                case "age_desc":
                    members = members.OrderByDescending(s => s.age_bracket);
                    break;
                case "gender":
                    members = members.OrderBy(s => s.gender);
                    break;
                case "gender_desc":
                    members = members.OrderByDescending(s => s.gender);
                    break;
                default:
                    members = members.OrderByDescending(s => s.confirmation_date);
                    break;
            }
            return View(await MembersPaginatedList<Member>.CreateAsync(members.AsNoTracking(), pageNumber ?? page, pageSize, pageLimit));
        }

        // GET: Members/Chart
        public async Task<IActionResult> Chart(string? groupBy)
        {
            string titleChart = "";
            string titleX = "";
            string[] setX = new string[0];
            string[] setY = new string[0];
            string getX = "";
            string getY = "";

            bool defView = true;
            switch (groupBy)
            {
                case "confirmation_date":
                    var query_confirmation_date = from s in _context.Member
                                                  orderby s.confirmation_date
                                                  group s by s.confirmation_date into g
                                                  select new
                                                  {
                                                      Date = g.Key,
                                                      Total = g.Count()
                                                  };
                    var res_confirmation_date = query_confirmation_date.OrderBy(s => s.Date);
                    foreach (var item in res_confirmation_date)
                    {
                        Array.Resize(ref setX, setX.Length + 1);
                        setX[setX.Length - 1] = item.Date.ToString();
                        Array.Resize(ref setY, setY.Length + 1);
                        setY[setY.Length - 1] = item.Total.ToString();
                    }
                    titleChart = "Group By Confirmation Date";
                    titleX = "Confirmation dates";
                    break;
                case "age_bracket":
                    var query_age_bracket = from s in _context.Member
                                            orderby s.age_bracket
                                            group s by s.age_bracket into g
                                            select new
                                            {
                                                Age = g.Key,
                                                Total = g.Count()
                                            };
                    var res_age_bracket = query_age_bracket.OrderBy(s => s.Age);
                    foreach (var item in res_age_bracket)
                    {
                        Array.Resize(ref setX, setX.Length + 1);
                        setX[setX.Length - 1] = item.Age;
                        Array.Resize(ref setY, setY.Length + 1);
                        setY[setY.Length - 1] = item.Total.ToString();
                    }
                    titleChart = "Group By Age Bracket";
                    titleX = "Age Brackets";
                    break;
                case "gender":
                    var query_gender = from s in _context.Member
                                       orderby s.gender
                                       group s by s.gender into g
                                       select new
                                       {
                                           Gender = g.Key,
                                           Total = g.Count()
                                       };
                    var res_gender = query_gender.OrderBy(s => s.Gender);
                    foreach (var item in res_gender)
                    {
                        Array.Resize(ref setX, setX.Length + 1);
                        setX[setX.Length - 1] = item.Gender;
                        Array.Resize(ref setY, setY.Length + 1);
                        setY[setY.Length - 1] = item.Total.ToString();
                    }
                    titleChart = "Group By Gender";
                    titleX = "Gender";
                    break;
                case "municipality_name":
                    var query_municipality_name = from s in _context.Member
                                                  orderby s.municipality_name
                                                  group s by s.municipality_name into g
                                                  select new
                                                  {
                                                      Name = g.Key,
                                                      Total = g.Count()
                                                  };
                    var res_municipality_name = query_municipality_name.OrderBy(s => s.Name);
                    foreach (var item in res_municipality_name)
                    {
                        Array.Resize(ref setX, setX.Length + 1);
                        setX[setX.Length - 1] = item.Name;
                        Array.Resize(ref setY, setY.Length + 1);
                        setY[setY.Length - 1] = item.Total.ToString();
                    }
                    titleChart = "Group By Municipality Name";
                    titleX = "Municipality Names";
                    break;
                case "age_gender":
                default:
                    defView = false;
                    var query_age_gender = from r in _context.Member
                                           group r by new { r.age_bracket, r.gender } into g
                                           orderby g.Key.age_bracket
                                           select new { Age = g.Key.age_bracket, Gender = g.Key.gender, Count = g.Count() };

                    var all_gender = from s in _context.Member
                                     orderby s.gender
                                     group s by s.gender into g
                                     select new
                                     {
                                         Gender = g.Key,
                                         Count = g.Key.Count()
                                     };

                    int[] temp = new int[0];
                    string[] gender = new string[0];

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <script src="js/microsoft/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/vue/dist/vue.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <div id="divToast" aria-live="polite" aria-atomic="true" style="display:block; position: absolute; left: 0; top: 0; z-index: 9999; padding:10px;">
    </div>
    @*<div class="progress" style="display:block; position: absolute; left: 0; right: 0; top: 0; z-index: 9999;">
            <div class="progress-bar progress-bar-striped bg-success" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="width: 10%; display:block; position: absolute; height: 50px; left: 0; right: 0; top: 0; z-index: 9999; padding:5px;"></div>
        </div>*@
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Index">Members</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Chart">Chart</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Database">Database</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AspNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/notifyHub.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>